export type OrganizationItem = {
  id: string;
  name: string;
  shortName?: string;
  legalForm?: string;
  inn?: string;
  kpp?: string;
  ogrn?: string;
  okpo?: string;
  phone?: string;
  email?: string;
  website?: string;
  legalAddress?: string;
  postalAddress?: string;
  bankName?: string;
  bankBik?: string;
  bankAccount?: string;
  bankCorrAccount?: string;
  signerName?: string;
  signerPosition?: string;
  notes?: string;
  country?: string;
  parentCounterparty?: string;
  createdAtSource?: string;
  registrationDate?: string;
  taxIdExtended?: string;
  kppExtended?: string;
  isBranch?: boolean;
  isInnValid?: boolean;
  isKppValid?: boolean;
  isGovernmentBody?: boolean;
  documentRef?: string;
  certificateSeriesNumber?: string;
  certificateIssuedDate?: string;
  governmentBodyType?: string;
  governmentBodyCode?: string;
  isActive: boolean;
  contactIds: string[];
  contactLabels: string[];
};

export type OrganizationItemInput = Omit<OrganizationItem, 'id'>;
