/**
 * JSON entry point для дизайнера.
 *
 * Логика:
 * - при старте приложения, если в `localStorage` нет кастомной темы (или она равна дефолту),
 *   будет применён этот JSON.
 * - чтобы увидеть изменения, обычно достаточно пересобрать фронт и перезайти на страницу.
 *
 * Вставляй сюда JSON формата `ThemeTokens` (как в `theme-schema.ts`).
 */
export const THEME_JSON_ENTRY_RAW = `{
  "name": "blueprint",
  "fontFamilyBase": "Inter, ui-sans-serif, system-ui, -apple-system, 'Segoe UI', Roboto, Arial, sans-serif",
  "fontSizeBase": "16px",
  "fontSizeLabel": "14px",
  "fontSizeSmall": "12px",
  "fontSizeCardTitle": "18px",
  "fontSizePageTitle": "28px",
  "textPrimary": "#101828",
  "textMuted": "rgba(16, 24, 40, 0.72)",
  "bgBase": "#f4f6fa",
  "bgGradientA": "rgba(31, 111, 235, 0.08)",
  "bgGradientB": "rgba(14, 159, 110, 0.08)",
  "surface": "rgba(255, 255, 255, 0.96)",
  "surfaceSoft": "rgba(249, 250, 251, 0.95)",
  "borderColor": "rgba(16, 24, 40, 0.14)",
  "shadowColor": "rgba(16, 24, 40, 0.04)",
  "accent": "#1f6feb",
  "success": "#0e9f6e",
  "danger": "#dc2626",
  "uiInputPaddingY": "8px",
  "uiInputPaddingX": "10px",
  "uiButtonPaddingY": "8px",
  "uiButtonPaddingX": "10px",
  "uiCardPadding": "16px",
  "uiCardMarginTop": "18px",
  "uiCardTitleMarginBottom": "12px",
  "uiFactPaddingY": "10px",
  "uiFactPaddingX": "12px",
  "uiFactLabelFontSize": "12px",
  "uiTableHeadPaddingY": "12px",
  "uiTableHeadPaddingX": "12px",
  "uiTableCellPaddingY": "11px",
  "uiTableCellPaddingX": "12px",
  "uiTableHeadFontSize": "13px",
  "uiTableCellFontSize": "14px",
  "uiModalBackdropPadding": "1rem",
  "uiModalHeaderPaddingY": "1rem",
  "uiModalHeaderPaddingX": "1.25rem",
  "uiModalTitleFontSize": "1.1rem",
  "uiModalContentPadding": "1.25rem",
  "uiModalActionsPaddingTop": "1rem",
  "uiModalActionsPaddingX": "1.25rem",
  "uiModalActionsPaddingBottom": "1.25rem",
  "uiAppHeaderPaddingY": "12px",
  "uiAppHeaderPaddingX": "16px",
  "uiNavGap": "8px",
  "uiNavLinkPaddingY": "6px",
  "uiNavLinkPaddingX": "10px",
  "uiPageShellPaddingTop": "24px",
  "uiPageShellPaddingX": "16px",
  "uiPageShellPaddingBottom": "48px",
  "uiSpace1": "4px",
  "uiRowActionBtnRadius": "8px",
  "uiShadowCardOffsetY": "8px",
  "uiShadowCardBlur": "24px",
  "uiShadowCardThinOffsetY": "1px",
  "uiSpace0p5": "6px",
  "uiSpace7": "7px",
  "uiSpace14": "14px",
  "uiSpace10": "10px",
  "uiBackdropBlurMd": "8px",
  "uiBackdropBlurSm": "6px",
  "uiControlMinHeight": "34px",
  "uiThemePickerMinWidth": "130px",
  "uiCrudActionsColWidth": "220px",
  "uiCrudCardLabelWidth": "140px",
  "uiModalShadowOffsetY": "20px",
  "uiModalShadowBlur": "40px",
  "radiusCard": "4px",
  "radiusPill": "4px"
}`;

