import { ThemeTokens } from './theme-schema';

export const THEME_PRESETS: ThemeTokens[] = [
  {
    name: 'blueprint',
    fontFamilyBase: "Inter, ui-sans-serif, system-ui, -apple-system, 'Segoe UI', Roboto, Arial, sans-serif",
    fontSizeBase: '16px',
    fontSizeLabel: '14px',
    fontSizeSmall: '12px',
    fontSizeCardTitle: '18px',
    fontSizePageTitle: '28px',
    textPrimary: '#101828',
    textMuted: 'rgba(16, 24, 40, 0.72)',
    bgBase: '#f4f6fa',
    bgGradientA: 'rgba(31, 111, 235, 0.08)',
    bgGradientB: 'rgba(14, 159, 110, 0.08)',
    surface: 'rgba(255, 255, 255, 0.96)',
    surfaceSoft: 'rgba(249, 250, 251, 0.95)',
    borderColor: 'rgba(16, 24, 40, 0.14)',
    shadowColor: 'rgba(16, 24, 40, 0.04)',
    accent: '#1f6feb',
    success: '#0e9f6e',
    iconAffirm: '#319432',
    iconAccent: '#1f6feb',
    iconMuted: 'rgba(16, 24, 40, 0.72)',
    iconWarning: '#f59e0b',
    iconDanger: '#dc2626',
    danger: '#dc2626',
    warning: '#f59e0b',
    uiInputPaddingY: '8px',
    uiInputPaddingX: '10px',
    uiButtonPaddingY: '8px',
    uiButtonPaddingX: '10px',
    uiButtonPrimaryBg: 'rgba(255, 255, 255, 0.96)',
    uiButtonPrimaryText: '#101828',
    uiButtonPrimaryBorderColor: 'rgba(16, 24, 40, 0.14)',
    uiButtonSoftBg: 'rgba(249, 250, 251, 0.95)',
    uiButtonSoftText: '#101828',
    uiButtonSoftBorderColor: 'rgba(16, 24, 40, 0.14)',
    uiCardPadding: '16px',
    uiCardMarginTop: '18px',
    uiCardTitleMarginBottom: '12px',
    uiFactPaddingY: '10px',
    uiFactPaddingX: '12px',
    uiFactLabelFontSize: '12px',
    uiTableHeadPaddingY: '12px',
    uiTableHeadPaddingX: '12px',
    uiTableCellPaddingY: '11px',
    uiTableCellPaddingX: '12px',
    uiTableHeadFontSize: '13px',
    uiTableCellFontSize: '14px',
    uiModalBackdropPadding: '1rem',
    uiModalHeaderPaddingY: '1rem',
    uiModalHeaderPaddingX: '1.25rem',
    uiModalTitleFontSize: '1.1rem',
    uiModalContentPadding: '1.25rem',
    uiModalActionsPaddingTop: '1rem',
    uiModalActionsPaddingX: '1.25rem',
    uiModalActionsPaddingBottom: '1.25rem',
    uiAppHeaderPaddingY: '12px',
    uiAppHeaderPaddingX: '16px',
    uiNavGap: '8px',
    uiNavLinkPaddingY: '6px',
    uiNavLinkPaddingX: '10px',
    uiPageShellPaddingTop: '24px',
    uiPageShellPaddingX: '16px',
    uiPageShellPaddingBottom: '48px',
    uiSpace1: '4px',
    uiRowActionBtnRadius: '8px',
    uiShadowCardOffsetY: '8px',
    uiShadowCardBlur: '24px',
    uiShadowCardThinOffsetY: '1px',
    uiSpace0p5: '6px',
    uiSpace7: '7px',
    uiSpace14: '14px',
    uiSpace10: '10px',
    uiBackdropBlurMd: '8px',
    uiBackdropBlurSm: '6px',
    uiControlMinHeight: '34px',
    uiThemePickerMinWidth: '130px',
    uiCrudActionsColWidth: '220px',
    uiCrudCardLabelWidth: '140px',
    uiModalShadowOffsetY: '20px',
    uiModalShadowBlur: '40px',
    radiusCard: '4px',
    radiusPill: '4px',
  },
  {
    name: 'dark',
    fontFamilyBase: "'Segoe UI', Inter, ui-sans-serif, system-ui, Arial, sans-serif",
    fontSizeBase: '16px',
    fontSizeLabel: '14px',
    fontSizeSmall: '12px',
    fontSizeCardTitle: '18px',
    fontSizePageTitle: '28px',
    // Enterprise-style dark (windows thick-client spirit).
    textPrimary: '#E6E6E6',
    textMuted: 'rgba(230, 230, 230, 0.72)',
    bgBase: '#1F1F22',
    bgGradientA: 'rgba(87, 147, 180, 0.16)',
    bgGradientB: 'rgba(109, 151, 129, 0.12)',
    surface: '#1F1F22',
    surfaceSoft: '#2D2D30',
    borderColor: '#4A4A4D',
    shadowColor: 'rgba(0, 0, 0, 0.55)',
    accent: '#5793B4',
    success: '#6D9781',
    iconAffirm: '#319432',
    iconAccent: '#5793B4',
    iconMuted: 'rgba(230, 230, 230, 0.72)',
    iconWarning: '#E3CB61',
    iconDanger: '#ED1C24',
    danger: '#ED1C24',
    warning: '#E3CB61',
    uiInputPaddingY: '8px',
    uiInputPaddingX: '10px',
    uiButtonPaddingY: '8px',
    uiButtonPaddingX: '10px',
    uiButtonPrimaryBg: '#E3CB61',
    uiButtonPrimaryText: '#1B1B1B',
    uiButtonPrimaryBorderColor: '#C9B768',
    uiButtonSoftBg: '#2D2D30',
    uiButtonSoftText: '#E6E6E6',
    uiButtonSoftBorderColor: '#4A4A4D',
    uiCardPadding: '16px',
    uiCardMarginTop: '18px',
    uiCardTitleMarginBottom: '12px',
    uiFactPaddingY: '10px',
    uiFactPaddingX: '12px',
    uiFactLabelFontSize: '12px',
    uiTableHeadPaddingY: '12px',
    uiTableHeadPaddingX: '12px',
    uiTableCellPaddingY: '11px',
    uiTableCellPaddingX: '12px',
    uiTableHeadFontSize: '13px',
    uiTableCellFontSize: '14px',
    uiModalBackdropPadding: '1rem',
    uiModalHeaderPaddingY: '1rem',
    uiModalHeaderPaddingX: '1.25rem',
    uiModalTitleFontSize: '1.1rem',
    uiModalContentPadding: '1.25rem',
    uiModalActionsPaddingTop: '1rem',
    uiModalActionsPaddingX: '1.25rem',
    uiModalActionsPaddingBottom: '1.25rem',
    uiAppHeaderPaddingY: '12px',
    uiAppHeaderPaddingX: '16px',
    uiNavGap: '8px',
    uiNavLinkPaddingY: '6px',
    uiNavLinkPaddingX: '10px',
    uiPageShellPaddingTop: '24px',
    uiPageShellPaddingX: '16px',
    uiPageShellPaddingBottom: '48px',
    uiSpace1: '4px',
    uiRowActionBtnRadius: '8px',
    uiShadowCardOffsetY: '8px',
    uiShadowCardBlur: '24px',
    uiShadowCardThinOffsetY: '1px',
    uiSpace0p5: '6px',
    uiSpace7: '7px',
    uiSpace14: '14px',
    uiSpace10: '10px',
    uiBackdropBlurMd: '8px',
    uiBackdropBlurSm: '6px',
    uiControlMinHeight: '34px',
    uiThemePickerMinWidth: '140px',
    uiCrudActionsColWidth: '220px',
    uiCrudCardLabelWidth: '140px',
    uiModalShadowOffsetY: '20px',
    uiModalShadowBlur: '40px',
    radiusCard: '6px',
    radiusPill: '4px',
  },
  {
    name: 'sand',
    fontFamilyBase: "'Trebuchet MS', Inter, ui-sans-serif, system-ui, Arial, sans-serif",
    fontSizeBase: '16px',
    fontSizeLabel: '14px',
    fontSizeSmall: '12px',
    fontSizeCardTitle: '18px',
    fontSizePageTitle: '28px',
    textPrimary: '#2d1f12',
    textMuted: 'rgba(45, 31, 18, 0.68)',
    bgBase: '#fff9ef',
    bgGradientA: 'rgba(255, 180, 95, 0.22)',
    bgGradientB: 'rgba(255, 124, 124, 0.16)',
    surface: 'rgba(255, 250, 241, 0.82)',
    surfaceSoft: 'rgba(255, 250, 241, 0.72)',
    borderColor: 'rgba(45, 31, 18, 0.10)',
    shadowColor: 'rgba(90, 52, 24, 0.12)',
    accent: '#dc7a2f',
    success: '#3aa85f',
    iconAffirm: '#319432',
    iconAccent: '#dc7a2f',
    iconMuted: 'rgba(45, 31, 18, 0.68)',
    iconWarning: '#f59e0b',
    iconDanger: '#d04949',
    danger: '#d04949',
    warning: '#f59e0b',
    uiInputPaddingY: '8px',
    uiInputPaddingX: '10px',
    uiButtonPaddingY: '8px',
    uiButtonPaddingX: '10px',
    uiButtonPrimaryBg: 'rgba(255, 250, 241, 0.82)',
    uiButtonPrimaryText: '#2d1f12',
    uiButtonPrimaryBorderColor: 'rgba(45, 31, 18, 0.10)',
    uiButtonSoftBg: 'rgba(255, 250, 241, 0.72)',
    uiButtonSoftText: '#2d1f12',
    uiButtonSoftBorderColor: 'rgba(45, 31, 18, 0.10)',
    uiCardPadding: '16px',
    uiCardMarginTop: '18px',
    uiCardTitleMarginBottom: '12px',
    uiFactPaddingY: '10px',
    uiFactPaddingX: '12px',
    uiFactLabelFontSize: '12px',
    uiTableHeadPaddingY: '12px',
    uiTableHeadPaddingX: '12px',
    uiTableCellPaddingY: '11px',
    uiTableCellPaddingX: '12px',
    uiTableHeadFontSize: '13px',
    uiTableCellFontSize: '14px',
    uiModalBackdropPadding: '1rem',
    uiModalHeaderPaddingY: '1rem',
    uiModalHeaderPaddingX: '1.25rem',
    uiModalTitleFontSize: '1.1rem',
    uiModalContentPadding: '1.25rem',
    uiModalActionsPaddingTop: '1rem',
    uiModalActionsPaddingX: '1.25rem',
    uiModalActionsPaddingBottom: '1.25rem',
    uiAppHeaderPaddingY: '12px',
    uiAppHeaderPaddingX: '16px',
    uiNavGap: '8px',
    uiNavLinkPaddingY: '6px',
    uiNavLinkPaddingX: '10px',
    uiPageShellPaddingTop: '24px',
    uiPageShellPaddingX: '16px',
    uiPageShellPaddingBottom: '48px',
    uiSpace1: '4px',
    uiRowActionBtnRadius: '8px',
    uiShadowCardOffsetY: '8px',
    uiShadowCardBlur: '24px',
    uiShadowCardThinOffsetY: '1px',
    uiSpace0p5: '6px',
    uiSpace7: '7px',
    uiSpace14: '14px',
    uiSpace10: '10px',
    uiBackdropBlurMd: '8px',
    uiBackdropBlurSm: '6px',
    uiControlMinHeight: '34px',
    uiThemePickerMinWidth: '130px',
    uiCrudActionsColWidth: '220px',
    uiCrudCardLabelWidth: '140px',
    uiModalShadowOffsetY: '20px',
    uiModalShadowBlur: '40px',
    radiusCard: '4px',
    radiusPill: '4px',
  },
  {
    name: 'light',
    fontFamilyBase: "'Segoe UI', Inter, ui-sans-serif, system-ui, Arial, sans-serif",
    fontSizeBase: '16px',
    fontSizeLabel: '14px',
    fontSizeSmall: '12px',
    fontSizeCardTitle: '18px',
    fontSizePageTitle: '28px',
    // Mimic a Windows thick-client look (grey panels + yellow primary buttons).
    textPrimary: '#3B3B3B',
    textMuted: 'rgba(91, 90, 92, 0.72)',
    bgBase: '#FFFFFF',
    bgGradientA: 'rgba(87, 147, 180, 0.10)',
    bgGradientB: 'rgba(109, 151, 129, 0.10)',
    surface: '#FFFFFF',
    surfaceSoft: '#D2D2D4',
    borderColor: '#ACACAE',
    shadowColor: 'rgba(33, 37, 41, 0.18)',
    accent: '#5793B4',
    success: '#6D9781',
    iconAffirm: '#319432',
    iconAccent: '#5793B4',
    iconMuted: 'rgba(91, 90, 92, 0.72)',
    iconWarning: '#E3CB61',
    iconDanger: '#ED1C24',
    danger: '#ED1C24',
    warning: '#E3CB61',
    uiInputPaddingY: '8px',
    uiInputPaddingX: '10px',
    uiButtonPaddingY: '8px',
    uiButtonPaddingX: '10px',
    uiButtonPrimaryBg: '#E3CB61',
    uiButtonPrimaryText: '#3B3B3B',
    uiButtonPrimaryBorderColor: '#C9B768',
    uiButtonSoftBg: '#D2D2D4',
    uiButtonSoftText: '#3B3B3B',
    uiButtonSoftBorderColor: '#ACACAE',
    uiCardPadding: '16px',
    uiCardMarginTop: '18px',
    uiCardTitleMarginBottom: '12px',
    uiFactPaddingY: '10px',
    uiFactPaddingX: '12px',
    uiFactLabelFontSize: '12px',
    uiTableHeadPaddingY: '12px',
    uiTableHeadPaddingX: '12px',
    uiTableCellPaddingY: '11px',
    uiTableCellPaddingX: '12px',
    uiTableHeadFontSize: '13px',
    uiTableCellFontSize: '14px',
    uiModalBackdropPadding: '1rem',
    uiModalHeaderPaddingY: '1rem',
    uiModalHeaderPaddingX: '1.25rem',
    uiModalTitleFontSize: '1.1rem',
    uiModalContentPadding: '1.25rem',
    uiModalActionsPaddingTop: '1rem',
    uiModalActionsPaddingX: '1.25rem',
    uiModalActionsPaddingBottom: '1.25rem',
    uiAppHeaderPaddingY: '12px',
    uiAppHeaderPaddingX: '16px',
    uiNavGap: '8px',
    uiNavLinkPaddingY: '6px',
    uiNavLinkPaddingX: '10px',
    uiPageShellPaddingTop: '24px',
    uiPageShellPaddingX: '16px',
    uiPageShellPaddingBottom: '48px',
    uiSpace1: '4px',
    uiRowActionBtnRadius: '8px',
    uiShadowCardOffsetY: '8px',
    uiShadowCardBlur: '24px',
    uiShadowCardThinOffsetY: '1px',
    uiSpace0p5: '6px',
    uiSpace7: '7px',
    uiSpace14: '14px',
    uiSpace10: '10px',
    uiBackdropBlurMd: '8px',
    uiBackdropBlurSm: '6px',
    uiControlMinHeight: '34px',
    uiThemePickerMinWidth: '140px',
    uiCrudActionsColWidth: '220px',
    uiCrudCardLabelWidth: '140px',
    uiModalShadowOffsetY: '20px',
    uiModalShadowBlur: '40px',
    radiusCard: '6px',
    radiusPill: '4px',
  },
];

export const defaultTheme =
  THEME_PRESETS.find((p) => p.name === 'light') ?? THEME_PRESETS[0];

