import { ThemeTokens } from './theme-schema';

export const THEME_PRESETS: ThemeTokens[] = [
  {
    name: 'blueprint',
    fontFamilyBase: "Inter, ui-sans-serif, system-ui, -apple-system, 'Segoe UI', Roboto, Arial, sans-serif",
    fontSizeBase: '16px',
    fontSizeLabel: '14px',
    fontSizeSmall: '12px',
    fontSizeCardTitle: '18px',
    fontSizePageTitle: '28px',
    textPrimary: '#101828',
    textMuted: 'rgba(16, 24, 40, 0.72)',
    bgBase: '#f4f6fa',
    bgGradientA: 'rgba(31, 111, 235, 0.08)',
    bgGradientB: 'rgba(14, 159, 110, 0.08)',
    surface: 'rgba(255, 255, 255, 0.96)',
    surfaceSoft: 'rgba(249, 250, 251, 0.95)',
    borderColor: 'rgba(16, 24, 40, 0.14)',
    shadowColor: 'rgba(16, 24, 40, 0.04)',
    accent: '#1f6feb',
    success: '#0e9f6e',
    danger: '#dc2626',
    uiInputPaddingY: '8px',
    uiInputPaddingX: '10px',
    uiButtonPaddingY: '8px',
    uiButtonPaddingX: '10px',
    uiCardPadding: '16px',
    uiCardMarginTop: '18px',
    uiCardTitleMarginBottom: '12px',
    uiFactPaddingY: '10px',
    uiFactPaddingX: '12px',
    uiFactLabelFontSize: '12px',
    uiTableHeadPaddingY: '12px',
    uiTableHeadPaddingX: '12px',
    uiTableCellPaddingY: '11px',
    uiTableCellPaddingX: '12px',
    uiTableHeadFontSize: '13px',
    uiTableCellFontSize: '14px',
    uiModalBackdropPadding: '1rem',
    uiModalHeaderPaddingY: '1rem',
    uiModalHeaderPaddingX: '1.25rem',
    uiModalTitleFontSize: '1.1rem',
    uiModalContentPadding: '1.25rem',
    uiModalActionsPaddingTop: '1rem',
    uiModalActionsPaddingX: '1.25rem',
    uiModalActionsPaddingBottom: '1.25rem',
    uiAppHeaderPaddingY: '12px',
    uiAppHeaderPaddingX: '16px',
    uiNavGap: '8px',
    uiNavLinkPaddingY: '6px',
    uiNavLinkPaddingX: '10px',
    uiPageShellPaddingTop: '24px',
    uiPageShellPaddingX: '16px',
    uiPageShellPaddingBottom: '48px',
    uiSpace1: '4px',
    uiRowActionBtnRadius: '8px',
    uiShadowCardOffsetY: '8px',
    uiShadowCardBlur: '24px',
    uiShadowCardThinOffsetY: '1px',
    uiSpace0p5: '6px',
    uiSpace7: '7px',
    uiSpace14: '14px',
    uiSpace10: '10px',
    uiBackdropBlurMd: '8px',
    uiBackdropBlurSm: '6px',
    uiControlMinHeight: '34px',
    uiThemePickerMinWidth: '130px',
    uiCrudActionsColWidth: '220px',
    uiCrudCardLabelWidth: '140px',
    uiModalShadowOffsetY: '20px',
    uiModalShadowBlur: '40px',
    radiusCard: '4px',
    radiusPill: '4px',
  },
  {
    name: 'graphite',
    fontFamilyBase: "'Segoe UI', Inter, ui-sans-serif, system-ui, Arial, sans-serif",
    fontSizeBase: '16px',
    fontSizeLabel: '14px',
    fontSizeSmall: '12px',
    fontSizeCardTitle: '18px',
    fontSizePageTitle: '28px',
    textPrimary: '#e5ecff',
    textMuted: 'rgba(229, 236, 255, 0.72)',
    bgBase: '#0d1118',
    bgGradientA: 'rgba(40, 130, 255, 0.20)',
    bgGradientB: 'rgba(0, 200, 170, 0.14)',
    surface: 'rgba(17, 25, 40, 0.70)',
    surfaceSoft: 'rgba(17, 25, 40, 0.56)',
    borderColor: 'rgba(190, 215, 255, 0.16)',
    shadowColor: 'rgba(0, 0, 0, 0.35)',
    accent: '#4e9cff',
    success: '#19c37d',
    danger: '#f87070',
    uiInputPaddingY: '8px',
    uiInputPaddingX: '10px',
    uiButtonPaddingY: '8px',
    uiButtonPaddingX: '10px',
    uiCardPadding: '16px',
    uiCardMarginTop: '18px',
    uiCardTitleMarginBottom: '12px',
    uiFactPaddingY: '10px',
    uiFactPaddingX: '12px',
    uiFactLabelFontSize: '12px',
    uiTableHeadPaddingY: '12px',
    uiTableHeadPaddingX: '12px',
    uiTableCellPaddingY: '11px',
    uiTableCellPaddingX: '12px',
    uiTableHeadFontSize: '13px',
    uiTableCellFontSize: '14px',
    uiModalBackdropPadding: '1rem',
    uiModalHeaderPaddingY: '1rem',
    uiModalHeaderPaddingX: '1.25rem',
    uiModalTitleFontSize: '1.1rem',
    uiModalContentPadding: '1.25rem',
    uiModalActionsPaddingTop: '1rem',
    uiModalActionsPaddingX: '1.25rem',
    uiModalActionsPaddingBottom: '1.25rem',
    uiAppHeaderPaddingY: '12px',
    uiAppHeaderPaddingX: '16px',
    uiNavGap: '8px',
    uiNavLinkPaddingY: '6px',
    uiNavLinkPaddingX: '10px',
    uiPageShellPaddingTop: '24px',
    uiPageShellPaddingX: '16px',
    uiPageShellPaddingBottom: '48px',
    uiSpace1: '4px',
    uiRowActionBtnRadius: '8px',
    uiShadowCardOffsetY: '8px',
    uiShadowCardBlur: '24px',
    uiShadowCardThinOffsetY: '1px',
    uiSpace0p5: '6px',
    uiSpace7: '7px',
    uiSpace14: '14px',
    uiSpace10: '10px',
    uiBackdropBlurMd: '8px',
    uiBackdropBlurSm: '6px',
    uiControlMinHeight: '34px',
    uiThemePickerMinWidth: '130px',
    uiCrudActionsColWidth: '220px',
    uiCrudCardLabelWidth: '140px',
    uiModalShadowOffsetY: '20px',
    uiModalShadowBlur: '40px',
    radiusCard: '4px',
    radiusPill: '4px',
  },
  {
    name: 'sand',
    fontFamilyBase: "'Trebuchet MS', Inter, ui-sans-serif, system-ui, Arial, sans-serif",
    fontSizeBase: '16px',
    fontSizeLabel: '14px',
    fontSizeSmall: '12px',
    fontSizeCardTitle: '18px',
    fontSizePageTitle: '28px',
    textPrimary: '#2d1f12',
    textMuted: 'rgba(45, 31, 18, 0.68)',
    bgBase: '#fff9ef',
    bgGradientA: 'rgba(255, 180, 95, 0.22)',
    bgGradientB: 'rgba(255, 124, 124, 0.16)',
    surface: 'rgba(255, 250, 241, 0.82)',
    surfaceSoft: 'rgba(255, 250, 241, 0.72)',
    borderColor: 'rgba(45, 31, 18, 0.10)',
    shadowColor: 'rgba(90, 52, 24, 0.12)',
    accent: '#dc7a2f',
    success: '#3aa85f',
    danger: '#d04949',
    uiInputPaddingY: '8px',
    uiInputPaddingX: '10px',
    uiButtonPaddingY: '8px',
    uiButtonPaddingX: '10px',
    uiCardPadding: '16px',
    uiCardMarginTop: '18px',
    uiCardTitleMarginBottom: '12px',
    uiFactPaddingY: '10px',
    uiFactPaddingX: '12px',
    uiFactLabelFontSize: '12px',
    uiTableHeadPaddingY: '12px',
    uiTableHeadPaddingX: '12px',
    uiTableCellPaddingY: '11px',
    uiTableCellPaddingX: '12px',
    uiTableHeadFontSize: '13px',
    uiTableCellFontSize: '14px',
    uiModalBackdropPadding: '1rem',
    uiModalHeaderPaddingY: '1rem',
    uiModalHeaderPaddingX: '1.25rem',
    uiModalTitleFontSize: '1.1rem',
    uiModalContentPadding: '1.25rem',
    uiModalActionsPaddingTop: '1rem',
    uiModalActionsPaddingX: '1.25rem',
    uiModalActionsPaddingBottom: '1.25rem',
    uiAppHeaderPaddingY: '12px',
    uiAppHeaderPaddingX: '16px',
    uiNavGap: '8px',
    uiNavLinkPaddingY: '6px',
    uiNavLinkPaddingX: '10px',
    uiPageShellPaddingTop: '24px',
    uiPageShellPaddingX: '16px',
    uiPageShellPaddingBottom: '48px',
    uiSpace1: '4px',
    uiRowActionBtnRadius: '8px',
    uiShadowCardOffsetY: '8px',
    uiShadowCardBlur: '24px',
    uiShadowCardThinOffsetY: '1px',
    uiSpace0p5: '6px',
    uiSpace7: '7px',
    uiSpace14: '14px',
    uiSpace10: '10px',
    uiBackdropBlurMd: '8px',
    uiBackdropBlurSm: '6px',
    uiControlMinHeight: '34px',
    uiThemePickerMinWidth: '130px',
    uiCrudActionsColWidth: '220px',
    uiCrudCardLabelWidth: '140px',
    uiModalShadowOffsetY: '20px',
    uiModalShadowBlur: '40px',
    radiusCard: '4px',
    radiusPill: '4px',
  },
  {
    name: 'Beethoven',
    fontFamilyBase: "'Georgia', ui-serif, 'Times New Roman', Times, serif",
    fontSizeBase: '16px',
    fontSizeLabel: '14px',
    fontSizeSmall: '12px',
    fontSizeCardTitle: '20px',
    fontSizePageTitle: '32px',
    textPrimary: '#F8FAFC',
    textMuted: 'rgba(248, 250, 252, 0.72)',
    bgBase: '#0B1020',
    bgGradientA: 'rgba(212, 175, 55, 0.12)',
    bgGradientB: 'rgba(46, 139, 87, 0.12)',
    surface: 'rgba(17, 25, 40, 0.76)',
    surfaceSoft: 'rgba(17, 25, 40, 0.58)',
    borderColor: 'rgba(212, 175, 55, 0.18)',
    shadowColor: 'rgba(0, 0, 0, 0.45)',
    accent: '#D4AF37',
    success: '#2E8B57',
    danger: '#B91C1C',
    uiInputPaddingY: '8px',
    uiInputPaddingX: '12px',
    uiButtonPaddingY: '8px',
    uiButtonPaddingX: '12px',
    uiCardPadding: '18px',
    uiCardMarginTop: '18px',
    uiCardTitleMarginBottom: '14px',
    uiFactPaddingY: '12px',
    uiFactPaddingX: '14px',
    uiFactLabelFontSize: '12px',
    uiTableHeadPaddingY: '13px',
    uiTableHeadPaddingX: '12px',
    uiTableCellPaddingY: '12px',
    uiTableCellPaddingX: '12px',
    uiTableHeadFontSize: '13px',
    uiTableCellFontSize: '14px',
    uiModalBackdropPadding: '1rem',
    uiModalHeaderPaddingY: '1rem',
    uiModalHeaderPaddingX: '1.25rem',
    uiModalTitleFontSize: '1.15rem',
    uiModalContentPadding: '1.25rem',
    uiModalActionsPaddingTop: '1rem',
    uiModalActionsPaddingX: '1.25rem',
    uiModalActionsPaddingBottom: '1.25rem',
    uiAppHeaderPaddingY: '12px',
    uiAppHeaderPaddingX: '16px',
    uiNavGap: '10px',
    uiNavLinkPaddingY: '7px',
    uiNavLinkPaddingX: '12px',
    uiPageShellPaddingTop: '28px',
    uiPageShellPaddingX: '16px',
    uiPageShellPaddingBottom: '56px',
    uiSpace1: '4px',
    uiRowActionBtnRadius: '8px',
    uiShadowCardOffsetY: '8px',
    uiShadowCardBlur: '24px',
    uiShadowCardThinOffsetY: '1px',
    uiSpace0p5: '6px',
    uiSpace7: '7px',
    uiSpace14: '14px',
    uiSpace10: '10px',
    uiBackdropBlurMd: '8px',
    uiBackdropBlurSm: '6px',
    uiControlMinHeight: '34px',
    uiThemePickerMinWidth: '140px',
    uiCrudActionsColWidth: '220px',
    uiCrudCardLabelWidth: '160px',
    uiModalShadowOffsetY: '20px',
    uiModalShadowBlur: '40px',
    radiusCard: '6px',
    radiusPill: '999px',
  },
];

export const defaultTheme = THEME_PRESETS[0];

