import type { KpCatalogProduct } from './kp-catalog-product.model';

/** Демо-ассортимент (без картинок). Рабочие товары — из API, с `imageUrl` с `/media/trade-goods/`. */
export const KP_CATALOG_DEMO_PRODUCTS: readonly KpCatalogProduct[] = [
  {
    id: 'p-1501',
    category: 'Уличные тренажёры «STREET IRON»',
    subcategory: 'Верх тела',
    title: 'Уличный тренажёр — Подтягивание «STREET IRON»',
    sku: 'УТ1501',
    price: 125_000,
    source: 'demo',
  },
  {
    id: 'p-1502',
    category: 'Уличные тренажёры «STREET IRON»',
    subcategory: 'Верх тела',
    title: 'Уличный тренажёр — Жим от плеч «STREET IRON»',
    sku: 'УТ1502',
    price: 125_000,
    source: 'demo',
  },
  {
    id: 'p-1503',
    category: 'Уличные тренажёры «STREET IRON»',
    subcategory: 'Верх тела',
    title: 'Уличный тренажёр — Тяга на себя «STREET IRON»',
    sku: 'УТ1503',
    price: 120_000,
    source: 'demo',
  },
  {
    id: 'p-1504',
    category: 'Уличные тренажёры «STREET IRON»',
    subcategory: 'Верх тела',
    title: 'Уличный тренажёр — Брусья/жим «STREET IRON»',
    sku: 'УТ1504',
    price: 119_000,
    source: 'demo',
  },
  {
    id: 'p-1601',
    category: 'Уличные тренажёры «STREET IRON»',
    subcategory: 'Спина и кор',
    title: 'Уличный тренажёр — Гиперэкстензия «STREET IRON»',
    sku: 'УТ1601',
    price: 132_000,
    source: 'demo',
  },
  {
    id: 'p-1602',
    category: 'Уличные тренажёры «STREET IRON»',
    subcategory: 'Спина и кор',
    title: 'Уличный тренажёр — Гребная тяга «STREET IRON»',
    sku: 'УТ1602',
    price: 128_000,
    source: 'demo',
  },
  {
    id: 'p-1701',
    category: 'Уличные тренажёры «STREET IRON»',
    subcategory: 'Ноги',
    title: 'Уличный тренажёр — Присед «STREET IRON»',
    sku: 'УТ1701',
    price: 109_000,
    source: 'demo',
  },
  {
    id: 'p-1702',
    category: 'Уличные тренажёры «STREET IRON»',
    subcategory: 'Ноги',
    title: 'Уличный тренажёр — Жим ногами «STREET IRON»',
    sku: 'УТ1702',
    price: 141_000,
    source: 'demo',
  },
  {
    id: 'p-1801',
    category: 'Уличные тренажёры «STREET IRON»',
    title: 'Уличный тренажёр — Степпер «STREET IRON»',
    sku: 'УТ1801',
    price: 98_000,
    source: 'demo',
  },
  {
    id: 'p-9001',
    category: 'Крепёж и аксессуары',
    subcategory: 'Метизы',
    title: 'Комплект крепления к анкерному основанию',
    sku: 'КР-9001',
    price: 4_500,
    source: 'demo',
  },
  {
    id: 'p-9002',
    category: 'Крепёж и аксессуары',
    subcategory: 'Покрытия площадки',
    title: 'Заглушка пластиковая для стоек (комплект 4 шт.)',
    sku: 'КР-9002',
    price: 890,
    source: 'demo',
  },
];
